name: Combine JSON Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  combine-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Merge JSON Files
        run: |
          jq -s 'reduce .[] as $item ({}; . * $item)' json/*.json > metadata.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add metadata.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update metadata.json"
          git push
